---

- name: Download Docker Compose binary
  become: true
  become_user: root
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'

- name: Check Docker Compose version
  become: true
  become_user: root
  command: docker-compose --version
  register: compose_version_output
  ignore_errors: true
